# Generated by Django 6.0.3 on 2026-05-18 02:00

import catastro.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unidad',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='condominio',
            name='categorias_documentos',
            field=models.CharField(blank=True, help_text='Separadas por comas', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='condominio',
            name='email_administracion',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='condominio',
            name='frecuencia_planes',
            field=models.CharField(choices=[('Anual', 'Anual'), ('Bianual', 'Bianual')], default='Anual', max_length=50),
        ),
        migrations.AddField(
            model_name='condominio',
            name='notificar_actualizacion_planes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='condominio',
            name='notificar_vencimiento_datos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='condominio',
            name='plantilla_planes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condominio',
            name='plantilla_vencimiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condominio',
            name='telefono_administracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='condicion_medica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residente',
            name='contacto_emergencia_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='contacto_emergencia_parentesco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='idioma_principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='movilidad_reducida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='recibir_notificaciones',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='relacion_jefe_hogar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residente',
            name='rut_dni',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='torre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='fecha_vencimiento_plan_emergencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='detalles_salud_sensibles',
            field=catastro.models.CustomEncryptedTextField(blank=True, help_text='Ej: tipo de movilidad reducida, enfermedades crónicas.', null=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PROPIETARIO', 'Propietario'), ('ARRENDATARIO', 'Arrendatario')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='unidad',
            unique_together={('condominio', 'torre', 'numero_depto')},
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo', models.FileField(upload_to='documentos_condominio/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='catastro.condominio')),
            ],
        ),
    ]
