# Generated by Django 6.0.3 on 2026-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0003_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
    ]
