# Generated by Django 6.0.3 on 2026-05-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0004_documento_fecha_emision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='residente',
            name='relacion_jefe_hogar',
            field=models.CharField(blank=True, choices=[('JEFE_HOGAR', 'Jefe de Hogar'), ('CONYUGE', 'Cónyuge'), ('ARRENDATARIO', 'Arrendatario'), ('FAMILIAR_MENOR', 'Familiar menor de edad'), ('FAMILIAR_ADULTO', 'Familiar adulto'), ('FAMILIAR_ADULTO_MAYOR', 'Familiar adulto mayor'), ('OTRO', 'Otro')], default='JEFE_HOGAR', max_length=30, null=True),
        ),
    ]
