# Generated by Django 6.0.3 on 2026-05-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0005_remove_residente_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='frecuencia_planes',
        ),
    ]
